EmreOrenRentACar/Areas/Admin/Controllers/HomeController.cs
using EmreOrenRentACar.Code;
using EmreOrenRentACar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace EmreOrenRentACar.Areas.Admin.Controllers
{
    [IsAdmin]
    public class HomeController : Controller
    {
        private RentalContext context = new RentalContext();

        // GET: Admin/Home
        public ActionResult Index()
        {
            var rentals = context.Rentals.Include(c => c.User).Include(c => c.Vehicle);
            return View(rentals.ToList());
        }
    }
}

EmreOrenRentACar/Areas/Admin/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmreOrenRentACar.Areas.Admin.Data;
using EmreOrenRentACar.Models;

namespace EmreOrenRentACar.Areas.Admin.Controllers
{
    public class VehicleController : Controller
    {
        private RentalContext db = new RentalContext();

        // GET: Admin/Vehicle
        public ActionResult Index()
        {
            var vehicles = db.Vehicles.Include(v => v.VehicleType);
            return View(vehicles.ToList());
        }

        // GET: Admin/Vehicle/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Admin/Vehicle/Create
        public ActionResult Create()
        {
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type");
            return View();
        }

        // POST: Admin/Vehicle/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Brand,Model,Year,Image,DailyPrice,VehicleTypeId")] VehicleDto input)
        {
            if (ModelState.IsValid)
            {
                string newfoto = null;
                if (input.Image != null && input.Image.ContentLength > 0)
                {
                    FileInfo fotoinfo = new FileInfo(input.Image.FileName);
                    newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;

                    string path = Path.Combine(Server.MapPath("~/Upload"),
                                               Path.GetFileName(newfoto));
                    input.Image.SaveAs(path);
                }
                var vehicle = new Vehicle()
                {
                    Brand = input.Brand,
                    DailyPrice = input.DailyPrice,
                    Image = newfoto != null ? ("/Upload/" + newfoto) : null,
                    Model = input.Model,
                    VehicleTypeId = input.VehicleTypeId,
                    Year = input.Year
                };

                db.Vehicles.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", input.VehicleTypeId);
            return View(input);
        }

        // GET: Admin/Vehicle/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var vehicle = db.Vehicles.Find(id);
            var result = new VehicleDto()
            {
                Id = vehicle.Id,
                Brand = vehicle.Brand,
                DailyPrice = vehicle.DailyPrice,
                OldImage = vehicle.Image,
                Image = null,
                Model = vehicle.Model,
                VehicleTypeId = vehicle.VehicleTypeId,
                Year = vehicle.Year
            };
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", result.VehicleTypeId);
            return View(result);
        }

        // POST: Admin/Vehicle/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Brand,Model,Year,Image,OldImage,DailyPrice,VehicleTypeId")] VehicleDto input)
        {
            if (ModelState.IsValid)
            {
                string newfoto = null;
                if (input.Image != null && input.Image.ContentLength > 0)
                {
                    FileInfo fotoinfo = new FileInfo(input.Image.FileName);
                    newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;

                    string path = Path.Combine(Server.MapPath("~/Upload"),
                                               Path.GetFileName(newfoto));
                    input.Image.SaveAs(path);
                }
                var vehicle = db.Vehicles.Include(y => y.VehicleType).FirstOrDefault(x => x.Id == input.Id);
                if (vehicle == null)
                {
                    Create(input);
                }
                else
                {
                    vehicle.Brand = input.Brand;
                    vehicle.DailyPrice = input.DailyPrice;
                    vehicle.Image = newfoto != null ? ("/Upload/" + newfoto) : input.OldImage;
                    vehicle.Model = input.Model;
                    vehicle.VehicleTypeId = input.VehicleTypeId;
                    vehicle.Year = input.Year;
                }

                db.Vehicles.Add(vehicle);
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", input.VehicleTypeId);
            return View(input);
        }

        // GET: Admin/Vehicle/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Admin/Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EmreOrenRentACar/Controllers/HomeController.cs
using EmreOrenRentACar.Dto;
using EmreOrenRentACar.Models;
using EmreOrenRentACar.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmreOrenRentACar.Controllers
{
  
    public class HomeController : Controller
    {
        RentalContext _context = new RentalContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View(new FilterInputDto());
        }

        [HttpPost]
        public ActionResult RenderList(FilterInputDto input)
        {
            var query = _context.Vehicles.Where(x => x.DailyPrice > input.minPrice && x.DailyPrice <= input.maxPrice).AsQueryable();

            if (input.filterText != null)
            {
                query = query.Where(x => x.Brand.Contains(input.filterText) || x.Model.Contains(input.filterText));
            }           
            if (input.orderByPrice)
            {
                query = query.OrderByDescending(x => x.DailyPrice);
            }
            else
            {
                query = query.OrderBy(x => x.DailyPrice);
            }
            List<VehicleDto> result = query.Select(x => new VehicleDto()
            {
                Id = x.Id,
                Brand = x.Brand,
                Model = x.Model,
                Image = x.Image,
                DailyPrice = x.DailyPrice,
                Year = x.Year
            }).ToList();
            return PartialView(new VehicleListViewModel()
            {
                Vehicles = result
            });
        }
    }
}

EmreOrenRentACar/Views/Home/Index.cshtml
@using EmreOrenRentACar.Dto;
@model FilterInputDto
@{
    ViewBag.Title = "Home Page";
}

<br />
<form>
    <div class="form-group">
        <label for="filterText">Anahtar Kelime</label>
        <input type="text" name="filterText" id="filterText" value="@Model.filterText" placeholder="Anahtar Kelime" class="form-control" />
    </div>
    <div class="form-group">
        <label for="min-max-label">Fiyata Göre Listele</label>
        <div class="col-12">
            <div class="row">
                <input type="number" name="minPrice" value="@Model.minPrice" id="minPrice" placeholder="En Düşük Fiyat" class="col-5 form-control" />
                <span class="col-2 text-center col-form-label">-</span>
                <input type="number" name="maxPrice" value="@Model.maxPrice" id="maxPrice" placeholder="En Yüksek Fiyat" class="col-5 form-control" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="orderBy" id="lth" checked>
            <label class="form-check-label" for="inlineCheckbox1">Küçükten Büyüğe</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="orderBy" id="htl">
            <label class="form-check-label" for="inlineCheckbox2">Büyükten Küçüğe</label>
        </div>
    </div>
    <div class="form-group">
        <div class="btn btn-sm btn-outline-success col-2 my-2 my-sm-0" onclick="getData()">Filtrele</div>
    </div>
</form>

<div class="row" id="renderList">

</div>

@section scripts{
    @*Notification*@
    @if (TempData["RentalSuccess"] != null)
    {
        <script>
            $(document).ready(function () {
                Swal.fire({
                    icon: 'success',
                    title: 'Başarılı...',
                    text: "@TempData["RentalSuccess"]",
                })
            });


        </script>
    }


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            //page load
            getData();
        })

        function getData() {
            var filterText = document.getElementById('filterText').value;
            var minPrice = document.getElementById('minPrice').value;
            var maxPrice = document.getElementById('maxPrice').value;
            var htl = document.getElementById('htl').checked;

            var filterData = {
                "filterText": filterText,
                "minPrice": minPrice,
                "maxPrice": maxPrice,
                "orderByPrice": htl ? true : false
            }

            $.ajax({
                type: "POST",
                url: "/Home/RenderList",
                data: filterData,
                dataType: "html",
                success: function (data) {
                    console.log(data)
                    $("#renderList").html(data);
                },
                error: function (result) {
                    console.log(result);
                    alert("hata");
                }
            });
        }
    </script>
}

EmreOrenRentACar/Views/Home/RenderList.cshtml
@using EmreOrenRentACar.ModelView;
@model VehicleListViewModel

@foreach (var vehicle in Model.Vehicles)
{
    <div class="col-4">
        <div class="card my-2">
            <img src="@vehicle.Image" class="card-img-top" alt="..." height="250">
            <div class="card-body">
                <h4 class="card-title"><a>@vehicle.Brand</a></h4>
                <h4 class="card-subtitle"><a>@vehicle.Model | @vehicle.DailyPrice.ToString("N2") ₺</a></h4>
                <br />
                <h6 class="card-subtitle">@vehicle.Year Model</h6>
            </div>
            <div class="card-body">
                @Html.ActionLink("Kirala", "Index", "Vehicle", new { id = vehicle.Id }, new { @class = "float-right btn btn-sm btn-outline-primary card-link" })
            </div>
        </div>
    </div>
}